config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :users
  resources :rooms
  resource :confirmation, :only => [:show]
  resource :user_sessions, :only => [:create, :new, :destroy]
  resources :rooms do
    resources :reviews, :only => [:create, :update], :module => :rooms 
  end

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :rooms, dependent: :destroy 
	has_many :reviews, dependent: :destroy 

  validates :email, presence: true 
  validates :email, format: { with: /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/ } 
  validates :full_name, presence: true 
  validates :location, presence: true 
  validates :bio, presence: true, length: { minimum: 10 }
  
  has_secure_password 

  before_create :generate_token

  scope :confirmed, -> { where('confirmed_at IS NOT NULL') }

  def generate_token 
		self.confirmation_token = SecureRandom.urlsafe_base64 
	end 

	def confirm! 
		return if confirmed?
		
		self.confirmed_at = Time.current 
		self.confirmation_token = '' 
		save! 
	end

	def confirmed?
		confirmed_at.present? 
	end

	def self.authenticate(email, password)
		# se confirmed? e password != nill
  	confirmed.find_by_email(email).try(:authenticate, password)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :can_change, :only => [:edit, :update, :destroy]
  before_filter :require_no_authentication, :only => [:new, :create] 

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        SignupMailer.confirm_email(@user).deliver
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:full_name, :email, :password, :location, :bio)
    end

    # verifica se o usuario pode fazer alterações no perfil
    def can_change 
      unless user_signed_in? && current_user == user 
        redirect_to user_path(params[:id]) 
      end 
    end

    def user 
      @user ||= User.find(params[:id])
    end 
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
       <%= t 'general.form_error' %>  
    </div>
  <% end %>
  <p>
    <%= f.label :full_name %>
    <%= f.text_field :full_name %>
    <%= error_tag @user, :full_name %>
  </p>
  <p>
    <%= f.label :location %>
    <%= f.text_field :location %>
    <%= error_tag @user, :location %>
  </p>
  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <%= error_tag @user, :email %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= error_tag @user, :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    <%= error_tag @user, :password_confirmation %>
  </p>
  <p>
    <%= f.label :bio %>
    <%= f.text_area :bio %>
    <%= error_tag @user, :bio %> 
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/users/edit.html.erb
<h1><%= t '.title' %></h1>

<%= render 'form' %>

<%= link_to t('links.show'), @user %> |
<%= link_to t('links.home'), users_path %>

app/views/users/index.html.erb
<h1><%= t('messages.listing') %></h1>

<table>
  <thead>
    <tr>
      <th><%= @users.model.human_attribute_name("full_name") %></th>
      <th><%= @users.model.human_attribute_name("location") %></th>
      <th><%= @users.model.human_attribute_name("email") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.full_name %></td>
        <td><%= user.location %></td>
        <td><%= user.email %></td>
        <td><%= link_to t('links.show'), user %></td>
        <td><%= link_to t('links.edit'), edit_user_path(user) %></td>
        <td><%= link_to t('links.destroy'), user, method: :delete, 
        data: { confirm: t('messages.confirm') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('links.new'), new_user_path %>

app/views/users/new.html.erb
<h1><%= t '.title' %></h1>

<%= render 'form' %>

<%= link_to t('links.back'), users_path %>

app/views/users/show.html.erb
<h1><%= t '.title', :user_name => @user.full_name %></h1>

<p>
  <strong><%= t('.full_name') %>:</strong>
  <%= @user.full_name %>
</p>

<p>
  <strong><%= t(".email") %>:</strong>
  <%= @user.email %>
</p>

<p>
  <strong><%= t(".location") %>:</strong>
  <%= @user.location %>
</p>

<p>
  <strong><%= t(".bio") %>:</strong>
  <%= @user.bio %>
</p>

<%= link_to t('links.edit'), edit_user_path(@user) %> |
<%= link_to t('links.home'), rooms_path %>