config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :users
  resources :rooms
  resource :confirmation, :only => [:show]
  resource :user_sessions, :only => [:create, :new, :destroy]
  resources :rooms do
    resources :reviews, :only => [:create, :update], :module => :rooms 
  end

end

app/models/room.rb
class Room < ActiveRecord::Base
  extend FriendlyId

  has_many :reviews, dependent: :destroy 
  has_many :reviewed_rooms, through: :reviews, source: :room
  belongs_to :user
  
  validates :title, presence: true 
  validates :location, presence: true 
  validates :description, presence: true, length: { minimum: 10 }
  validates :slug, presence: true
  validates :picture, presence: true

  friendly_id :title, use: [:slugged, :finders]
  mount_uploader :picture, PictureUploader 
  scope :most_recent, -> { order('created_at DESC') }
  
  def complete_name 
    "#{title}, #{location}"
  end 

  def self.search(query) 
    if query.present? 
      where(['location LIKE :query OR title LIKE :query 
        OR description LIKE :query', :query => "%#{query}%"])
    else
      all
    end
  end

end

app/controllers/rooms/reviews_controller.rb
class Rooms::ReviewsController < ApplicationController 
	before_filter :require_authentication
	
	def create 
		review = room.reviews.find_or_initialize_by(user_id: current_user.id)
		review.update_attributes!(review_params)
		head :ok 
	end

	def update 
		create 
	end

	private

	def room 
		@room ||= Room.find(params[:room_id]) 
	end

	def review_params
		params.require(:review).permit(:points)
	end
	
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  PER_PAGE = 2

  before_action :set_users_room, only: [:edit, :update, :destroy]
  before_filter :require_authentication, :only => [:new, :edit, :create, :update, :destroy]

  def index
    @search_query = params[:q]
    rooms = Room.search(@search_query).page(params[:page]).per(PER_PAGE)
    @rooms = RoomCollectionPresenter.new(rooms.most_recent, self) 


    #@rooms = rooms.most_recent.map do |room|
    #  RoomPresenter.new(room, self, false)
    #end
  end

  def show
    room_model = Room.find(params[:id])
    @room = RoomPresenter.new(room_model, self)
  end

  def new
    @room = current_user.rooms.build
  end

  def edit
  end

  def create
    @room = current_user.rooms.build(room_params)

    if @room.save
      redirect_to @room, notice: t('flash.notice.room_created') 
    else
      render :new 
    end
  end

  def update
    if @room.update(room_params)
      redirect_to @room, notice: t('flash.notice.room_updated') 
    else
      render :edit 
    end
  end

  def destroy
    @room.destroy
    redirect_to rooms_url, notice: t('flash.notice.room_destroyed') 
  end

  private
    def set_room
      @room = Rooms.find(params[:id])
    end

    def set_users_room
      @room = current_user.rooms.find(params[:id])
    end

    def room_params
      params.require(:room).permit(:title, :location, :description, :picture)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
	def belongs_to_user(room) 
		user_signed_in? && room.user == current_user 
	end 
end

app/views/rooms/_form.html.erb
<%= form_for @room , html: { multipart: true } do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <%= t 'general.form_error' %>
    </div>
  <% end %>

  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= error_tag @room, :title %>
  </p>
  <p>
    <%= f.label :location %>
    <%= f.text_field :location %>
    <%= error_tag @room, :location %>
  </p>
  <p>
    <%= f.label :description %>
    <%= f.text_area :description %>
    <%= error_tag @room, :description %>
  </p>
  <p>
    <%= f.label :picture %>
    <%= f.file_field :picture %>
    <%= error_tag @room, :picture %>
  </p> 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/rooms/_review.html.erb
<section class="review">
	<% if room.show_form? %>
		<%= render partial: 'review_form', locals: {:room => room} %>
	<% else %>
		<% room.stars.times do %>
			<span class="star filled_star"></span>
		<% end %>

		<% (room.review_points.max - room.stars).times do %> 
			<span class="star empty_star"></span> 
		<% end %>

		<%= t '.stats', :count => room.total_reviews %> 
	<% end %> 
</section>

app/views/rooms/_review_form.html.erb
<% if room.can_review? %>
	<%= form_for room.review_route, remote: true do |f| %>
		<% room.review_points.each do |point| %>
			<%= f.radio_button :points, point %>
			<%= f.label :points, value: point do %> 
				<i class="star empty_star"></i>
			<% end %> 
		<% end %>
		<%= f.submit %> 
	<% end %> 
<% else %> 
	<span class="login_required"> 
		<%= t('.login_to_review') %>
	</span> 
<% end %>

app/views/rooms/_room.html.erb
<article class="room"> 
  <%= link_to(image_tag(room.thumb_url), room.picture_url, target: :blank) if room.has_picture? %>

  <h2><%= link_to highlight(room.title, @search_query), room.route %></h2>

  <%= render partial: 'review', locals: {room: room} %>

  <span class="created">
    <%= t '.owner_html', owner: room.user.full_name, when: l(room.created_at, format: :short) %>
  </span> 
  <p> 
    <span class="location"> 
      <%= link_to room.location, "https://maps.google.com/?q=#{room.location}",target: :blank %>
    </span> 
  </p>
  <p>
    <%= highlight(room.description, @search_query) %>
  </p> 
  <p>
    <%= room.description %>
  </p>
  <% if belongs_to_user(room) %>
    <ul> 
      <li><%= link_to t('links.edit'), edit_room_path(room.route) %></li> 
      <li>
        <%= link_to t('links.destroy'), room_path(room.route), 
        method: :delete, 
        data: { confirm: t('messages.confirm') } %>
      </li> 
    </ul> 
  <% end %> 
</article> 

app/views/rooms/_search.html.erb
<%= form_tag rooms_path, method: :get, class: 'search' do %> 
	<%= text_field_tag :q, @search_query, placeholder: t('.search_for') %> 
<% end %>

app/views/rooms/edit.html.erb
<h1><%= t '.title' %></h1>

<%= render 'form' %>

<%= link_to t('links.show'), @room %> |
<%= link_to t('links.home'), rooms_path %>

app/views/rooms/index.html.erb
<%= render 'search' %>

<h1>
	<% if @search_query.present? %> 
		<%= t '.search_results' %> 
	<% else %> 
		<%= t '.title' %>
	<% end %>
</h1>


<%= render @rooms %>

<%= paginate @rooms %>

app/views/rooms/new.html.erb
<h1><%= t '.title' %></h1>

<%= render 'form' %>

<%= link_to t('links.back'), rooms_path %>

app/views/rooms/show.html.erb
<h1><%= t '.title' %></h1>

<%= render @room %>